<a href="https://colab.research.google.com/github/sakshii951/DSPY_25-26/blob/main/Notebook14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NOTEBOOK 1: Data Selection, Cleaning & Wrangling
##Step 1: Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import re

## Step 2: Load Dataset

In [ ]:
df = pd.read_csv('sample_data/spam.csv', encoding='latin-1')
df.head()

  label                                           message
0   ham                        Hi how are you doing today
1  spam                          Win money now click here
2   ham                    Let's meet tomorrow at college
3  spam  Congratulations you have won a lottery claim now
4   ham                         Can you send me the notes

##Step 3: Basic Information of Dataset

In [ ]:
df.shape
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    200 non-null    object
 1   message  200 non-null    object
dtypes: object(2)
memory usage: 3.3+ KB

       label                     message
count    200                         200
unique     2                          20
top      ham  Hi how are you doing today
freq     100                          10

## 4. Attribute Selection
### Selected Attributes:
* label → Target variable (Spam or Ham)
* message → Text data
###  Reason:
* label is required for classification
* message contains actual content for analysis

## Step 5: Check Missing Values

In [ ]:
df.isnull().sum()

label      0
message    0
dtype: int64

## Observation:
* No missing values (or mention if present)

  ## Step 6: Check Duplicate Values

In [ ]:
df.duplicated().sum()

np.int64(180)

### Reomve duplicate

In [ ]:
df.drop_duplicates(inplace=True)

## Step 7: Data Type Description
|Column|	Data Type|	Description|
|------|-----------|-------------|
label	|Object (Categorical)|	Spam or Ham
message|	Object (Text)|	Email/SMS content

In [ ]:
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

##Step 8: Text Cleaning

In [ ]:
import re
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub('[^a-zA-Z]', ' ', text)  # Remove special characters
    text = re.sub(r'\s+',' ', text)  # Remove extra spaces
    return text

df['message'] = df['message'].apply(clean_text)

## Final Dataset

In [ ]:
df.head()

   label                                           message
0      0                        hi how are you doing today
1      1                          win money now click here
2      0                    let s meet tomorrow at college
3      1  congratulations you have won a lottery claim now
4      0                         can you send me the notes

##Save Cleaned Dataset

In [ ]:
df.to_csv('cleaned_spam.csv', index=False)